name: Test action
on: push
jobs:
  first-job:
    name: Build something
    runs-on: windows-latest
    steps:
      - run: node --version
      - run: npm i express
      - run: node server.js