name: Test action
on: push
jobs:
  first-job:
    name: Build something
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: node ./server.js

